### ISSUE TITLE
make operationName a constant inside the duck

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/redux-operations-counter-example#2]
@DrorT I'm not really sure what you had envisioned for this, so I'll leave it in your capable hands! If you need help just shoot me a gist & we'll figure it out.

**Comment by DrorT** [comment]
sent a PR for this, what do you think?

**Comment by mattkrick** [comment]
i think it's about as clean as it can get now. only real coding challenge left is https://github.com/mattkrick/redux-operations/issues/8
